Add windows support
conda-forge/maven-feedstock pull request #2
Opened 2017-04-20 12:52 UTC by hadim

2017-04-20 12:52 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2017-04-20 13:25 UTC, johanneskoester requested changes
Thanks! I guess you also need to rerender the feedstock with conda-smithy in order to get appveyor running.

2017-04-20 13:25 UTC, johanneskoester commented on recipe/meta.yaml
> +{% set sha256 = "beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034" %}
I prefer to only use variables for stuff that occurs more than once in the recipe.

2017-04-20 13:55 UTC, johanneskoester approved these changes

2017-04-21 01:52 UTC, hadim commented
LGTM @johanneskoester

2017-04-21 08:13 UTC, merged