remove openjdk upper bound limit
conda-forge/maven-feedstock pull request #37
Opened 2024-06-28 14:49 UTC by jdmarques

Hello, I think you should remove this upper limit on the OpenJDK. From the Maven documentation, the limit is only on JDK 8,  " Maven 3.9+ requires JDK 8 or above to execute" source: https://maven.apache.org/download.cgi

why set this upper bound limit?

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-06-28 15:46 UTC, mariusvniekerk approved these changes

2024-06-28 16:33 UTC, mkitti commented
There have been some conda-forge specific issues here in the past. What we really need here are better tests.

My bandwidth as a maintainer is limited until mid-July. I would be willing to do a trial then

If you would like to see proceed before then, please add additional tests across multiple platforms.

2024-06-28 16:38 UTC, mkitti requested changes
Additional testing is required to confidently lift the upper bound on openjdk particularly due to past issues on Windows.

2024-06-28 16:39 UTC, mkitti commented
There have been some conda-forge specific issues here in the past. What we really need here are better tests.

My bandwidth as a maintainer is limited until mid-July. I would be willing to do a trial then

If you would like to see proceed before then, please add additional tests across multiple platforms.

See
https://github.com/conda-forge/maven-feedstock/pull/24#issuecomment-1588465291

2024-07-01 15:50 UTC, jdmarques commented
hello @mkitti,
from what I see in https://github.com/conda-forge/maven-feedstock/pull/24#issuecomment-1588465291 what fixed the issue was the flag to ignore the cleanup errors "-Dmaven.clean.failOnError=false" and not the version limit. Am I missing something?

From the CI logs the build from this PR run with "openjdk:             22.0.1-h57928b3_0       conda-forge" just fine. I can try to add a test but I need more information about the actual issue.

2024-07-15 17:28 UTC, mkitti commented
I have some bandwidth to try this now, and plan to merge in a few hours.

Pinging @ctrueden and @hinerm

2024-07-15 21:35 UTC, mkitti commented
@conda-forge-admin, please rerender

2024-07-15 22:38 UTC, merged

2024-07-16 08:20 UTC, jdmarques commented
thanks @mkitti